@startuml
'https://plantuml.com/sequence-diagram

Пользователь -> Оформление: Начало оформления товара

== Предварительная проверка ==
Оформление --> "Складской учет": Проверка наличия
Оформление -[#AA0000]> Пользователь: Нет в наличии

== Процесс оплаты ==
Оформление --> "Платежный шлюз": Проведение оплаты
group Сценарий ошибки оплаты
    "Платежный шлюз" --> Оформление  : Оплата не удалась оплаты
    Оформление -[#AA0000]> Пользователь: Ошибка оплаты
end
group Успешное списание средств у пользователя
    "Платежный шлюз" --> Оформление  : Заказ успешно оплачен
    Оформление --> EDA_storage: order_payed
    EDA_storage --> "Складской учет": order_payed
    "Складской учет" --> "Складской учет": резервирование заказа
    group Успешное резервирование заказа
        "Складской учет" --> EDA_storage: delivery
        EDA_storage --> Оформление: delivery
        Оформление -[#00AA00]> Пользователь: Заказ успешно создан
    end
    group Ошибка резервирование товара
        "Складской учет" --> EDA_storage: delivery_fail
        EDA_storage --> "Платежный шлюз": delivery_fail
        "Платежный шлюз" --> "Платежный шлюз": Возврат средств
        "Платежный шлюз" --> EDA_storage: refund_succeeded

        EDA_storage --> Оформление: delivery_fail
        EDA_storage --> Оформление: refund_succeeded
        Оформление -[#AA0000]> Пользователь: Ошибка создания заказа, средства возвращены
    end
end

@enduml